name: HQarroum/awesome-iot
author:
  name: Halim Qarroum
  email: hqm.post@gmail.com
  url: 'http://halim.qarroum.com'
copyright: 2015 Halim Qarroum
description: A curated list of awesome Internet of Things projects and resources.
